// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Decoder(	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7]
  input  [31:0] io_instr,	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
  output [3:0]  io_instrType,	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
  output [1:0]  io_fuType,	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
  output [7:0]  io_opType,	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
  output [4:0]  io_rs1,	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
                io_rs2,	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
                io_rd,	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
  output [31:0] io_imm,	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
  output [11:0] io_csrAddr	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:42:14]
);

  wire [9:0]  _GEN = {io_instr[14:12], io_instr[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_1 = _GEN == 10'h13;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire [16:0] _GEN_0 = {io_instr[31:25], io_instr[14:12], io_instr[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_3 = _GEN_0 == 17'h93;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_5 = _GEN == 10'h113;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_7 = _GEN == 10'h193;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_9 = _GEN == 10'h213;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_11 = _GEN_0 == 17'h293;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_13 = _GEN == 10'h313;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_15 = _GEN == 10'h393;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_17 = _GEN_0 == 17'h8293;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_19 = _GEN_0 == 17'h33;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_21 = _GEN_0 == 17'hB3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_23 = _GEN_0 == 17'h133;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_25 = _GEN_0 == 17'h1B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_27 = _GEN_0 == 17'h233;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_29 = _GEN_0 == 17'h2B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_31 = _GEN_0 == 17'h333;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_33 = _GEN_0 == 17'h3B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_35 = _GEN_0 == 17'h8033;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_37 = _GEN_0 == 17'h82B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_43 = io_instr[6:0] == 7'h6F;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_45 = _GEN == 10'h67;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_47 = _GEN == 10'h63;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_49 = _GEN == 10'hE3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_51 = _GEN == 10'h263;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_53 = _GEN == 10'h2E3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_55 = _GEN == 10'h363;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_57 = _GEN == 10'h3E3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_59 = _GEN == 10'h3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_61 = _GEN == 10'h83;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_63 = _GEN == 10'h103;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_65 = _GEN == 10'h203;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_67 = _GEN == 10'h283;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_69 = _GEN == 10'h23;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_71 = _GEN == 10'hA3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_73 = _GEN == 10'h123;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_75 = io_instr == 32'h73;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_77 = io_instr == 32'h30200073;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_79 = _GEN == 10'hF3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_81 = _GEN == 10'h173;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decodeResult_T_83 = _GEN == 10'h1F3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _GEN_1 =
    _decodeResult_T_75 | _decodeResult_T_77 | _decodeResult_T_79 | _decodeResult_T_81
    | _decodeResult_T_83;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_2 = _decodeResult_T_69 | _decodeResult_T_71 | _decodeResult_T_73;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_3 =
    _decodeResult_T_47 | _decodeResult_T_49 | _decodeResult_T_51 | _decodeResult_T_53
    | _decodeResult_T_55 | _decodeResult_T_57;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_4 = io_instr[6:0] == 7'h17 | io_instr[6:0] == 7'h37;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire [2:0]  decodeResult_0 =
    _decodeResult_T_1 | _decodeResult_T_3 | _decodeResult_T_5 | _decodeResult_T_7
    | _decodeResult_T_9 | _decodeResult_T_11 | _decodeResult_T_13 | _decodeResult_T_15
    | _decodeResult_T_17
      ? 3'h4
      : _decodeResult_T_19 | _decodeResult_T_21 | _decodeResult_T_23 | _decodeResult_T_25
        | _decodeResult_T_27 | _decodeResult_T_29 | _decodeResult_T_31
        | _decodeResult_T_33 | _decodeResult_T_35 | _decodeResult_T_37
          ? 3'h5
          : _GEN_4
              ? 3'h6
              : _decodeResult_T_43
                  ? 3'h7
                  : _decodeResult_T_45
                      ? 3'h4
                      : _GEN_3
                          ? 3'h1
                          : _decodeResult_T_59 | _decodeResult_T_61 | _decodeResult_T_63
                            | _decodeResult_T_65 | _decodeResult_T_67
                              ? 3'h4
                              : _GEN_2 ? 3'h2 : {_GEN_1, 2'h0};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire [1:0]  io_fuType_0 =
    _decodeResult_T_1 | _decodeResult_T_3 | _decodeResult_T_5 | _decodeResult_T_7
    | _decodeResult_T_9 | _decodeResult_T_11 | _decodeResult_T_13 | _decodeResult_T_15
    | _decodeResult_T_17 | _decodeResult_T_19 | _decodeResult_T_21 | _decodeResult_T_23
    | _decodeResult_T_25 | _decodeResult_T_27 | _decodeResult_T_29 | _decodeResult_T_31
    | _decodeResult_T_33 | _decodeResult_T_35 | _decodeResult_T_37 | _GEN_4
      ? 2'h0
      : _decodeResult_T_43 | _decodeResult_T_45 | _GEN_3
          ? 2'h3
          : _decodeResult_T_59 | _decodeResult_T_61 | _decodeResult_T_63
            | _decodeResult_T_65 | _decodeResult_T_67 | _GEN_2
              ? 2'h1
              : {_GEN_1, 1'h0};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _io_rd_T = decodeResult_0 == 3'h5;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:79:30, src/main/scala/chisel3/util/Lookup.scala:34:39]
  reg  [31:0] casez_tmp;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:82:41]
  wire [19:0] _GEN_5 = {20{io_instr[31]}};	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:83:28]
  always_comb begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:82:41]
    casez (decodeResult_0)	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:82:41, src/main/scala/chisel3/util/Lookup.scala:34:39]
      3'b000:
        casez_tmp = 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:82:41]
      3'b001:
        casez_tmp =
          {{20{io_instr[31]}}, io_instr[7], io_instr[30:25], io_instr[11:8], 1'h0};	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:71:{28,42,55,73}, :82:41, :85:28, src/main/scala/chisel3/util/Lookup.scala:34:39]
      3'b010:
        casez_tmp = {_GEN_5, io_instr[31:25], io_instr[11:7]};	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:62:24, :66:24, :82:41, :83:28, :84:28]
      3'b011:
        casez_tmp = 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:82:41]
      3'b100:
        casez_tmp = {_GEN_5, io_instr[31:20]};	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:67:24, :82:41, :83:28]
      3'b101:
        casez_tmp = 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:82:41]
      3'b110:
        casez_tmp = {io_instr[31:12], 12'h0};	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:72:{19,28}, :82:41]
      default:
        casez_tmp =
          {{12{io_instr[31]}}, io_instr[19:12], io_instr[20], io_instr[30:21], 1'h0};	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:71:28, :73:{42,60,74}, :82:41, :87:28, src/main/scala/chisel3/util/Lookup.scala:34:39]
    endcase	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:82:41, src/main/scala/chisel3/util/Lookup.scala:34:39]
  end // always_comb
  assign io_instrType = {1'h0, decodeResult_0};	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7, :57:16, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_fuType = io_fuType_0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_opType =
    {1'h0,
     _decodeResult_T_1
       ? 7'h40
       : _decodeResult_T_3
           ? 7'h1
           : _decodeResult_T_5
               ? 7'h2
               : _decodeResult_T_7
                   ? 7'h3
                   : _decodeResult_T_9
                       ? 7'h4
                       : _decodeResult_T_11
                           ? 7'h5
                           : _decodeResult_T_13
                               ? 7'h6
                               : _decodeResult_T_15
                                   ? 7'h7
                                   : _decodeResult_T_17
                                       ? 7'hD
                                       : _decodeResult_T_19
                                           ? 7'h40
                                           : _decodeResult_T_21
                                               ? 7'h1
                                               : _decodeResult_T_23
                                                   ? 7'h2
                                                   : _decodeResult_T_25
                                                       ? 7'h3
                                                       : _decodeResult_T_27
                                                           ? 7'h4
                                                           : _decodeResult_T_29
                                                               ? 7'h5
                                                               : _decodeResult_T_31
                                                                   ? 7'h6
                                                                   : _decodeResult_T_33
                                                                       ? 7'h7
                                                                       : _decodeResult_T_35
                                                                           ? 7'h8
                                                                           : _decodeResult_T_37
                                                                               ? 7'hD
                                                                               : _GEN_4
                                                                                   ? 7'h40
                                                                                   : _decodeResult_T_43
                                                                                       ? 7'hF
                                                                                       : _decodeResult_T_45
                                                                                           ? 7'hE
                                                                                           : _decodeResult_T_47
                                                                                               ? 7'h5
                                                                                               : _decodeResult_T_49
                                                                                                   ? 7'hB
                                                                                                   : _decodeResult_T_51
                                                                                                       ? 7'h9
                                                                                                       : _decodeResult_T_53
                                                                                                           ? 7'h7
                                                                                                           : _decodeResult_T_55
                                                                                                               ? 7'h8
                                                                                                               : _decodeResult_T_57
                                                                                                                   ? 7'h6
                                                                                                                   : _decodeResult_T_59
                                                                                                                       ? 7'h0
                                                                                                                       : _decodeResult_T_61
                                                                                                                           ? 7'h1
                                                                                                                           : _decodeResult_T_63
                                                                                                                               ? 7'h2
                                                                                                                               : _decodeResult_T_65
                                                                                                                                   ? 7'h4
                                                                                                                                   : _decodeResult_T_67
                                                                                                                                       ? 7'h5
                                                                                                                                       : _decodeResult_T_69
                                                                                                                                           ? 7'h8
                                                                                                                                           : _decodeResult_T_71
                                                                                                                                               ? 7'h9
                                                                                                                                               : _decodeResult_T_73
                                                                                                                                                   ? 7'hA
                                                                                                                                                   : _decodeResult_T_75
                                                                                                                                                     | _decodeResult_T_77
                                                                                                                                                       ? 7'h0
                                                                                                                                                       : _decodeResult_T_79
                                                                                                                                                           ? 7'h1
                                                                                                                                                           : _decodeResult_T_81
                                                                                                                                                               ? 7'h2
                                                                                                                                                               : _decodeResult_T_83
                                                                                                                                                                   ? 7'h3
                                                                                                                                                                   : 7'h40};	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7, :59:16, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  assign io_rs1 = io_instr[19:15];	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7, :64:24]
  assign io_rs2 =
    _io_rd_T | decodeResult_0 == 3'h2 | decodeResult_0 == 3'h1 ? io_instr[24:20] : 5'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7, :65:24, :79:{16,30,57,68,84}, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_rd =
    _io_rd_T | decodeResult_0 == 3'h4 | decodeResult_0 == 3'h6 | (&decodeResult_0)
      ? io_instr[11:7]
      : 5'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7, :62:24, :79:{16,30}, :80:{16,57,84,95,111}, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_imm = casez_tmp;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7, :82:41]
  assign io_csrAddr = io_fuType_0 == 2'h2 ? io_instr[31:20] : 12'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/decoder.scala:41:7, :67:24, :72:19, :76:25, :91:20, src/main/scala/chisel3/util/Lookup.scala:34:39]
endmodule

module ALU(	// @[home/lj/Desktop/C_stage_core/playground/src/core/ALU.scala:19:7]
  input  [31:0] io_in1,	// @[home/lj/Desktop/C_stage_core/playground/src/core/ALU.scala:20:14]
                io_in2,	// @[home/lj/Desktop/C_stage_core/playground/src/core/ALU.scala:20:14]
  input  [6:0]  io_opType,	// @[home/lj/Desktop/C_stage_core/playground/src/core/ALU.scala:20:14]
  output [31:0] io_result	// @[home/lj/Desktop/C_stage_core/playground/src/core/ALU.scala:20:14]
);

  wire [62:0] _io_result_T_8 = {31'h0, io_in1} << io_in2[4:0];	// @[home/lj/Desktop/C_stage_core/playground/src/core/ALU.scala:31:{47,56}]
  wire [31:0] _GEN = {27'h0, io_in2[4:0]};	// @[home/lj/Desktop/C_stage_core/playground/src/core/ALU.scala:31:56, :32:47]
  assign io_result =
    io_opType == 7'h40
      ? io_in1 + io_in2
      : io_opType == 7'h8
          ? io_in1 - io_in2
          : io_opType == 7'h1
              ? _io_result_T_8[31:0]
              : io_opType == 7'h5
                  ? io_in1 >> _GEN
                  : io_opType == 7'hD
                      ? $signed($signed(io_in1) >>> _GEN)
                      : io_opType == 7'h4
                          ? io_in1 ^ io_in2
                          : io_opType == 7'h6
                              ? io_in1 | io_in2
                              : io_opType == 7'h7
                                  ? io_in1 & io_in2
                                  : {31'h0,
                                     io_opType == 7'h2
                                       ? $signed(io_in1) < $signed(io_in2)
                                       : io_opType == 7'h3 & io_in1 < io_in2};	// @[home/lj/Desktop/C_stage_core/playground/src/core/ALU.scala:19:7, :29:{16,47}, :30:{16,47}, :31:{16,47}, :32:{16,47}, :33:{16,54}, :34:{16,47}, :35:{16,47}, :36:{16,47}, :37:{16,54}, :38:{16,47}, src/main/scala/chisel3/util/Mux.scala:126:16]
endmodule

module BRU(	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:18:7]
  input  [31:0] io_rs1,	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:19:14]
                io_rs2,	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:19:14]
  input  [3:0]  io_opType,	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:19:14]
  output        io_branchTaken	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:19:14]
);

  wire [31:0] _diff_T = io_rs1 - io_rs2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:26:21]
  wire        signedLessThan =
    io_rs1[31] != io_rs2[31] & _diff_T[31] != io_rs1[31] ? io_rs1[31] : _diff_T[31];	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:26:21, :27:{31,36,46,52,60,65}, :32:33]
  wire        isUnsignedLessThan = io_rs1 < io_rs2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:34:35]
  assign io_branchTaken =
    io_opType == 4'h6
      ? ~isUnsignedLessThan
      : io_opType == 4'h8
          ? isUnsignedLessThan
          : io_opType == 4'h7
              ? ~signedLessThan
              : io_opType == 4'h9
                  ? signedLessThan
                  : io_opType == 4'hB
                      ? (|_diff_T)
                      : io_opType == 4'h5
                          ? ~(|_diff_T)
                          : io_opType == 4'hE | (&io_opType);	// @[home/lj/Desktop/C_stage_core/playground/src/core/BRU.scala:18:7, :26:21, :29:22, :32:33, :34:35, :36:50, :42:23, :44:23]
endmodule

module PCU(	// @[home/lj/Desktop/C_stage_core/playground/src/core/PCU.scala:13:7]
  input  [31:0] io_pc,	// @[home/lj/Desktop/C_stage_core/playground/src/core/PCU.scala:14:14]
                io_rs1,	// @[home/lj/Desktop/C_stage_core/playground/src/core/PCU.scala:14:14]
                io_offset,	// @[home/lj/Desktop/C_stage_core/playground/src/core/PCU.scala:14:14]
  input  [3:0]  io_opType,	// @[home/lj/Desktop/C_stage_core/playground/src/core/PCU.scala:14:14]
  output [31:0] io_dnpc	// @[home/lj/Desktop/C_stage_core/playground/src/core/PCU.scala:14:14]
);

  wire [31:0] _io_dnpc_T_4 = io_pc + io_offset;	// @[home/lj/Desktop/C_stage_core/playground/src/core/PCU.scala:23:31]
  assign io_dnpc =
    io_opType == 4'h0
      ? io_rs1
      : io_opType == 4'h4
          ? io_pc + 32'h4
          : io_opType == 4'h5
              ? _io_dnpc_T_4
              : io_opType == 4'hE
                  ? io_rs1 + io_offset
                  : (&io_opType) ? _io_dnpc_T_4 : io_pc;	// @[home/lj/Desktop/C_stage_core/playground/src/core/PCU.scala:13:7, :22:41, :23:31, :24:32, :26:30]
endmodule

module LSU(	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:25:7]
  input  [31:0] io_addr,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
                io_dataIn,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  input  [3:0]  io_mask,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  input         io_wen,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
                io_ren,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
                io_sign,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  output [31:0] io_rdata,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  input  [31:0] io_mem_readData,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  output        io_mem_readEnable,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  output [31:0] io_mem_addr,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  output        io_mem_writeEnable,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  output [3:0]  io_mem_writeMask,	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
  output [31:0] io_mem_writeData	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:26:14]
);

  reg [31:0] casez_tmp;	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:47:39]
  always_comb begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:47:39]
    casez (io_addr[1:0])	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:38:28, :47:39]
      2'b00:
        casez_tmp = {{24{io_mem_readData[7]}}, io_mem_readData[7:0]};	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:47:39, :48:{17,22,34,47}]
      2'b01:
        casez_tmp = {{24{io_mem_readData[15]}}, io_mem_readData[15:8]};	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:47:39, :49:{17,22,34,48}]
      2'b10:
        casez_tmp = {{24{io_mem_readData[23]}}, io_mem_readData[23:16]};	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:47:39, :50:{17,22,34,48}]
      default:
        casez_tmp = {{24{io_mem_readData[31]}}, io_mem_readData[31:24]};	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:47:39, :51:{17,22,34,48}]
    endcase	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:38:28, :47:39]
  end // always_comb
  reg [7:0]  casez_tmp_0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:54:39, :55:17, :56:17, :57:17, :58:17]
  always_comb begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:54:39, :55:17, :56:17, :57:17, :58:17]
    casez (io_addr[1:0])	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:38:28, :54:39, :55:17, :56:17, :57:17, :58:17]
      2'b00:
        casez_tmp_0 = io_mem_readData[7:0];	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:48:47, :54:39, :55:17, :56:17, :57:17, :58:17]
      2'b01:
        casez_tmp_0 = io_mem_readData[15:8];	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:49:48, :54:39, :55:17, :56:17, :57:17, :58:17]
      2'b10:
        casez_tmp_0 = io_mem_readData[23:16];	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:50:48, :54:39, :55:17, :56:17, :57:17, :58:17]
      default:
        casez_tmp_0 = io_mem_readData[31:24];	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:51:48, :54:39, :55:17, :56:17, :57:17, :58:17]
    endcase	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:38:28, :54:39, :55:17, :56:17, :57:17, :58:17]
  end // always_comb
  assign io_rdata =
    io_ren
      ? ((&io_mask)
           ? io_mem_readData
           : io_mask == 4'h3
               ? (io_sign
                    ? (io_addr[1]
                         ? {{16{io_mem_readData[31]}}, io_mem_readData[31:16]}
                         : {{16{io_mem_readData[15]}}, io_mem_readData[15:0]})
                    : {16'h0,
                       io_addr[1] ? io_mem_readData[31:16] : io_mem_readData[15:0]})
               : io_mask == 4'h1 ? (io_sign ? casez_tmp : {24'h0, casez_tmp_0}) : 32'h0)
      : 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:25:7, :43:{16,54}, :45:19, :47:39, :48:22, :49:34, :51:34, :54:39, :55:17, :56:17, :57:17, :58:17, :63:19, :65:{8,16}, :66:{10,15,41}, :67:{10,15,41}, :70:8, :71:10, :72:10]
  assign io_mem_readEnable = io_ren;	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:25:7]
  assign io_mem_addr = io_addr;	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:25:7]
  assign io_mem_writeEnable = io_wen;	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:25:7]
  assign io_mem_writeMask = io_wen ? io_mask : 4'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:25:7, :81:28]
  assign io_mem_writeData = io_wen ? io_dataIn : 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:25:7, :43:54, :84:28]
endmodule

module CSRU(	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
  input         clock,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
                reset,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
  input  [2:0]  io_csrOpType,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
  input         io_csrCmd_valid,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
  input  [11:0] io_csrCmd_addr,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
  input  [31:0] io_csrCmd_rs1,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
  input         io_privOp_mret,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
                io_privOp_ecall,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
  input  [31:0] io_privOp_pc,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
  output [31:0] io_rdata,	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
                io_dnpc	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
);

  reg  [31:0] csrState_mstatus;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
  reg  [31:0] csrState_mepc;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
  reg  [31:0] csrState_mcause;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
  reg  [31:0] csrState_mtvec;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
  wire        _GEN = io_csrCmd_addr == 12'h300;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:78:26]
  wire        _GEN_0 = io_csrCmd_addr == 12'h341;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:78:26]
  wire        _GEN_1 = io_csrCmd_addr == 12'h342;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:78:26]
  wire        _GEN_2 = io_csrCmd_addr == 12'h305;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:78:26]
  wire [31:0] csrReadData =
    _GEN
      ? csrState_mstatus
      : _GEN_0
          ? csrState_mepc
          : _GEN_1 ? csrState_mcause : _GEN_2 ? csrState_mtvec : 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29, :78:26, :79:42, :80:42, :81:42, :82:42]
  wire [12:0] _GEN_3 = csrState_mstatus[12:0] | {9'h0, csrState_mstatus[7], 3'h0};	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :67:25, :96:{46,67,77}]
  wire        _io_trap_T = io_csrOpType == 3'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :92:21]
  wire        _GEN_4 = io_csrOpType == 3'h1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :109:48]
  wire        _GEN_5 = io_csrOpType == 3'h2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:82]
  wire        _GEN_6 = io_csrOpType == 3'h3;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
  wire        _GEN_7 = io_csrCmd_valid & (_GEN_4 | _GEN_5 | _GEN_6);	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:{31,48,82,100,116}]
  wire [31:0] _csrNewValue_T = csrReadData | io_csrCmd_rs1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:78:26, :79:42, :113:54]
  wire [31:0] _csrNewValue_T_2 = csrReadData & ~io_csrCmd_rs1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:78:26, :79:42, :114:{54,56}]
  wire        _GEN_8 = _io_trap_T | ~_GEN_7;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:86:29, :92:{21,40}, :109:{31,136}]
  always @(posedge clock) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
    if (reset) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
      csrState_mstatus <= 32'h1800;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :69:18]
      csrState_mepc <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
      csrState_mcause <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
      csrState_mtvec <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
    end
    else begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
      if (_io_trap_T) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:92:21]
        if (io_privOp_ecall) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
          csrState_mstatus <=
            {21'h3,
             csrState_mstatus[10:8],
             csrState_mstatus[3],
             csrState_mstatus[6:0] & 7'h77};	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :101:36, :102:{24,45,47,58}]
          csrState_mepc <= io_privOp_pc;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
          csrState_mcause <= 32'hB;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, src/main/scala/chisel3/util/Mux.scala:126:16]
        end
        else if (io_privOp_mret)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:36:14]
          csrState_mstatus <= {19'h0, {_GEN_3[12:8], _GEN_3[7:0] | 8'h80} & 13'h7FF};	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :96:{46,67,84}, :97:{42,44}]
      end
      else begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:92:21]
        if (_GEN_7 & _GEN) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :78:26, :109:{31,136}, :117:28, :118:49]
          if (_GEN_8)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:86:29, :92:40, :109:136]
            csrState_mstatus <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
          else if (_GEN_4)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:48]
            csrState_mstatus <= io_csrCmd_rs1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
          else if (_GEN_5)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:82]
            csrState_mstatus <= _csrNewValue_T;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :113:54]
          else if (_GEN_6)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
            csrState_mstatus <= _csrNewValue_T_2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :114:54]
          else	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
            csrState_mstatus <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
        end
        if (~_GEN_7 | _GEN | ~_GEN_0) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :78:26, :86:29, :92:40, :109:{31,136}, :117:28]
        end
        else if (_GEN_8)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:86:29, :92:40, :109:136]
          csrState_mepc <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
        else if (_GEN_4)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:48]
          csrState_mepc <= io_csrCmd_rs1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
        else if (_GEN_5)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:82]
          csrState_mepc <= _csrNewValue_T;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :113:54]
        else if (_GEN_6)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
          csrState_mepc <= _csrNewValue_T_2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :114:54]
        else	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
          csrState_mepc <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
        if (~_GEN_7 | _GEN | _GEN_0 | ~_GEN_1) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :78:26, :86:29, :92:40, :109:{31,136}, :117:28]
        end
        else if (_GEN_8)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:86:29, :92:40, :109:136]
          csrState_mcause <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
        else if (_GEN_4)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:48]
          csrState_mcause <= io_csrCmd_rs1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
        else if (_GEN_5)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:82]
          csrState_mcause <= _csrNewValue_T;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :113:54]
        else if (_GEN_6)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
          csrState_mcause <= _csrNewValue_T_2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :114:54]
        else	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
          csrState_mcause <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
      end
      if (_io_trap_T | ~_GEN_7 | _GEN | _GEN_0 | _GEN_1 | ~_GEN_2) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :78:26, :86:29, :92:{21,40}, :109:{31,136}, :117:28]
      end
      else if (_GEN_8)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:86:29, :92:40, :109:136]
        csrState_mtvec <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
      else if (_GEN_4)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:48]
        csrState_mtvec <= io_csrCmd_rs1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25]
      else if (_GEN_5)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:82]
        csrState_mtvec <= _csrNewValue_T;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :113:54]
      else if (_GEN_6)	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
        csrState_mtvec <= _csrNewValue_T_2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :114:54]
      else	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:109:116]
        csrState_mtvec <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:67:25, :77:29]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
      `FIRRTL_BEFORE_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
    initial begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
        `INIT_RANDOM_PROLOG_	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
        end	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
        csrState_mstatus = _RANDOM[2'h0];	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :67:25]
        csrState_mepc = _RANDOM[2'h1];	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :67:25]
        csrState_mcause = _RANDOM[2'h2];	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :67:25]
        csrState_mtvec = _RANDOM[2'h3];	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :67:25]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
      `FIRRTL_AFTER_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rdata = csrReadData;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :78:26, :79:42]
  assign io_dnpc = io_privOp_ecall ? csrState_mtvec : csrState_mepc;	// @[home/lj/Desktop/C_stage_core/playground/src/core/CSR.scala:35:7, :67:25, :126:17]
endmodule

// external module Memory

// external module DPIModule

module RegFile(	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
  input         clock,	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
                reset,	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
  input  [4:0]  io_rs1,	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:7:14]
                io_rs2,	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:7:14]
                io_rd,	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:7:14]
  input         io_wen,	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:7:14]
  input  [31:0] io_wdata,	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:7:14]
  output [31:0] io_rdata1,	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:7:14]
                io_rdata2	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:7:14]
);

  reg  [31:0] regs_0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_3;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_4;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_5;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_6;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_7;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_8;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_9;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_10;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_11;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_12;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_13;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_14;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_15;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_16;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_17;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_18;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_19;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_20;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_21;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_22;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_23;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_24;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_25;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_26;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_27;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_28;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_29;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_30;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] regs_31;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  reg  [31:0] casez_tmp;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:18:19]
  always_comb begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:18:19]
    casez (io_rs1)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:18:19]
      5'b00000:
        casez_tmp = regs_0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00001:
        casez_tmp = regs_1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00010:
        casez_tmp = regs_2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00011:
        casez_tmp = regs_3;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00100:
        casez_tmp = regs_4;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00101:
        casez_tmp = regs_5;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00110:
        casez_tmp = regs_6;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00111:
        casez_tmp = regs_7;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01000:
        casez_tmp = regs_8;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01001:
        casez_tmp = regs_9;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01010:
        casez_tmp = regs_10;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01011:
        casez_tmp = regs_11;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01100:
        casez_tmp = regs_12;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01101:
        casez_tmp = regs_13;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01110:
        casez_tmp = regs_14;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01111:
        casez_tmp = regs_15;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10000:
        casez_tmp = regs_16;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10001:
        casez_tmp = regs_17;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10010:
        casez_tmp = regs_18;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10011:
        casez_tmp = regs_19;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10100:
        casez_tmp = regs_20;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10101:
        casez_tmp = regs_21;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10110:
        casez_tmp = regs_22;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10111:
        casez_tmp = regs_23;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11000:
        casez_tmp = regs_24;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11001:
        casez_tmp = regs_25;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11010:
        casez_tmp = regs_26;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11011:
        casez_tmp = regs_27;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11100:
        casez_tmp = regs_28;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11101:
        casez_tmp = regs_29;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11110:
        casez_tmp = regs_30;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      default:
        casez_tmp = regs_31;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
    endcase	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:18:19]
  end // always_comb
  reg  [31:0] casez_tmp_0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:19:19]
  always_comb begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:18:19]
    casez (io_rs2)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:18:19]
      5'b00000:
        casez_tmp_0 = regs_0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00001:
        casez_tmp_0 = regs_1;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00010:
        casez_tmp_0 = regs_2;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00011:
        casez_tmp_0 = regs_3;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00100:
        casez_tmp_0 = regs_4;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00101:
        casez_tmp_0 = regs_5;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00110:
        casez_tmp_0 = regs_6;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b00111:
        casez_tmp_0 = regs_7;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01000:
        casez_tmp_0 = regs_8;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01001:
        casez_tmp_0 = regs_9;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01010:
        casez_tmp_0 = regs_10;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01011:
        casez_tmp_0 = regs_11;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01100:
        casez_tmp_0 = regs_12;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01101:
        casez_tmp_0 = regs_13;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01110:
        casez_tmp_0 = regs_14;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b01111:
        casez_tmp_0 = regs_15;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10000:
        casez_tmp_0 = regs_16;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10001:
        casez_tmp_0 = regs_17;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10010:
        casez_tmp_0 = regs_18;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10011:
        casez_tmp_0 = regs_19;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10100:
        casez_tmp_0 = regs_20;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10101:
        casez_tmp_0 = regs_21;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10110:
        casez_tmp_0 = regs_22;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b10111:
        casez_tmp_0 = regs_23;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11000:
        casez_tmp_0 = regs_24;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11001:
        casez_tmp_0 = regs_25;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11010:
        casez_tmp_0 = regs_26;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11011:
        casez_tmp_0 = regs_27;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11100:
        casez_tmp_0 = regs_28;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11101:
        casez_tmp_0 = regs_29;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      5'b11110:
        casez_tmp_0 = regs_30;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
      default:
        casez_tmp_0 = regs_31;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :18:19]
    endcase	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:18:19]
  end // always_comb
  wire        _GEN = io_wen & (|io_rd);	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:21:{21,30}]
  always @(posedge clock) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
    if (reset) begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
      regs_0 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_1 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_2 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_3 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_4 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_5 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_6 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_7 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_8 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_9 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_10 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_11 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_12 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_13 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_14 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_15 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_16 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_17 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_18 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_19 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_20 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_21 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_22 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_23 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_24 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_25 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_26 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_27 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_28 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_29 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_30 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      regs_31 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
    end
    else begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
      regs_0 <= 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:{27,35}]
      if (_GEN & io_rd == 5'h1)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_1 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h2)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_2 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h3)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_3 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h4)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_4 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h5)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_5 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h6)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_6 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h7)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_7 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h8)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_8 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h9)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_9 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'hA)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_10 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'hB)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_11 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'hC)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_12 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'hD)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_13 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'hE)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_14 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'hF)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_15 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h10)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_16 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h11)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_17 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h12)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_18 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h13)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_19 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h14)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_20 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h15)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_21 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h16)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_22 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h17)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_23 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h18)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_24 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h19)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_25 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h1A)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_26 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h1B)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_27 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h1C)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_28 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h1D)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_29 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & io_rd == 5'h1E)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27, :21:{21,39}, :22:23]
        regs_30 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
      if (_GEN & (&io_rd))	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27, :21:{21,39}, :22:23]
        regs_31 <= io_wdata;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:31];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
    initial begin	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
        end	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
        regs_0 = _RANDOM[5'h0];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_1 = _RANDOM[5'h1];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_2 = _RANDOM[5'h2];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_3 = _RANDOM[5'h3];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_4 = _RANDOM[5'h4];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_5 = _RANDOM[5'h5];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_6 = _RANDOM[5'h6];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_7 = _RANDOM[5'h7];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_8 = _RANDOM[5'h8];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_9 = _RANDOM[5'h9];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_10 = _RANDOM[5'hA];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_11 = _RANDOM[5'hB];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_12 = _RANDOM[5'hC];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_13 = _RANDOM[5'hD];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_14 = _RANDOM[5'hE];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_15 = _RANDOM[5'hF];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_16 = _RANDOM[5'h10];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_17 = _RANDOM[5'h11];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_18 = _RANDOM[5'h12];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_19 = _RANDOM[5'h13];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_20 = _RANDOM[5'h14];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_21 = _RANDOM[5'h15];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_22 = _RANDOM[5'h16];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_23 = _RANDOM[5'h17];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_24 = _RANDOM[5'h18];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_25 = _RANDOM[5'h19];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_26 = _RANDOM[5'h1A];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_27 = _RANDOM[5'h1B];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_28 = _RANDOM[5'h1C];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_29 = _RANDOM[5'h1D];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_30 = _RANDOM[5'h1E];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
        regs_31 = _RANDOM[5'h1F];	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :16:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  DPIModule dpiRegFile (	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:28:28]
    .regs_0  (regs_0),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_1  (regs_1),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_2  (regs_2),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_3  (regs_3),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_4  (regs_4),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_5  (regs_5),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_6  (regs_6),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_7  (regs_7),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_8  (regs_8),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_9  (regs_9),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_10 (regs_10),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_11 (regs_11),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_12 (regs_12),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_13 (regs_13),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_14 (regs_14),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_15 (regs_15),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_16 (regs_16),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_17 (regs_17),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_18 (regs_18),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_19 (regs_19),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_20 (regs_20),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_21 (regs_21),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_22 (regs_22),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_23 (regs_23),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_24 (regs_24),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_25 (regs_25),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_26 (regs_26),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_27 (regs_27),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_28 (regs_28),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_29 (regs_29),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_30 (regs_30),	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
    .regs_31 (regs_31)	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:16:27]
  );
  assign io_rdata1 = casez_tmp;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :18:19]
  assign io_rdata2 = casez_tmp_0;	// @[home/lj/Desktop/C_stage_core/playground/src/core/regfile.scala:6:7, :19:19]
endmodule

module top(	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
  input         clock,	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
                reset,	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
  input  [31:0] io_instr,	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:61:14]
  output [31:0] io_pc,	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:61:14]
                io_dnpc	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:61:14]
);

  wire [31:0] result;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:155:31, :157:12, :158:36, :160:12, :161:37]
  wire [3:0]  _decoder_io_opType_3to0;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:152:17]
  wire [31:0] _regfile_io_rdata1;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:75:23]
  wire [31:0] _regfile_io_rdata2;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:75:23]
  wire [31:0] _memory_readData;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:73:22]
  wire [31:0] _csr_io_rdata;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:72:19]
  wire [31:0] _csr_io_dnpc;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:72:19]
  wire [31:0] _lsu_io_rdata;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
  wire        _lsu_io_mem_readEnable;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
  wire [31:0] _lsu_io_mem_addr;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
  wire        _lsu_io_mem_writeEnable;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
  wire [3:0]  _lsu_io_mem_writeMask;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
  wire [31:0] _lsu_io_mem_writeData;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
  wire [31:0] _pcu_io_dnpc;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:70:19]
  wire        _bru_io_branchTaken;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:69:19]
  wire [31:0] _alu_io_result;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:68:19]
  wire [3:0]  _decoder_io_instrType;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
  wire [1:0]  _decoder_io_fuType;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
  wire [7:0]  _decoder_io_opType;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
  wire [4:0]  _decoder_io_rs1;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
  wire [4:0]  _decoder_io_rs2;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
  wire [4:0]  _decoder_io_rd;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
  wire [31:0] _decoder_io_imm;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
  wire [11:0] _decoder_io_csrAddr;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
  reg  [31:0] pcReg;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:78:22]
  wire        _GEN = _decoder_io_instrType == 4'h4 | _decoder_io_instrType == 4'h2;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :99:{18,29,42}, :216:19]
  wire        _GEN_0 = _decoder_io_instrType == 4'h6;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :102:24]
  wire [31:0] in1 = _GEN | ~_GEN_0 ? _regfile_io_rdata1 : io_instr[5] ? 32'h0 : pcReg;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:75:23, :78:22, :99:{29,54}, :100:9, :102:{24,35}, :106:{15,24}]
  wire [31:0] in2 = _GEN | _GEN_0 ? _decoder_io_imm : _regfile_io_rdata2;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :75:23, :99:{29,54}, :101:9, :102:{24,35}, :107:9, :110:9]
  wire        _csr_io_privOp_ecall_T = _decoder_io_fuType == 2'h2;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :99:42, :115:34]
  wire        _csr_io_privOp_ecall_T_1 = _decoder_io_opType[2:0] == 3'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :114:20, :115:71, :119:70]
  wire        _GEN_1 = _decoder_io_fuType == 2'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :99:42, :130:15]
  wire        _GEN_2 = _decoder_io_fuType == 2'h1;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :133:21]
  wire        _GEN_3 = _GEN_2 & ~(_decoder_io_opType[3]);	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:15:39, :16:34, home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :133:{21,36}]
  wire        _GEN_4 = _decoder_io_opType_3to0 == 4'hE;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:136:89, :152:17]
  wire        _GEN_5 = (&_decoder_io_fuType) & ((&_decoder_io_opType_3to0) | _GEN_4);	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :136:{21,36,54,72,89}, :152:17]
  wire        _GEN_6 = _csr_io_privOp_ecall_T & (|(_decoder_io_opType[2:0]));	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :114:20, :115:{34,71}, :139:36]
  assign _decoder_io_opType_3to0 = _decoder_io_opType[3:0];	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :152:17]
  assign result =
    _GEN_1 | _GEN_2
      ? _alu_io_result
      : (&_decoder_io_fuType) ? {31'h0, _bru_io_branchTaken} : 32'h0;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :68:19, :69:19, :106:15, :130:15, :133:21, :136:21, :155:31, :157:12, :158:36, :160:12, :161:37, :163:12, :166:12]
  wire        _GEN_7 = _GEN_2 & _decoder_io_opType[3];	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:15:39, home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :133:21, :170:30]
  wire        _GEN_8 = (&_decoder_io_fuType) & result == 32'h1;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :136:21, :155:31, :157:12, :158:36, :160:12, :161:37, :193:{30,40}]
  wire        _GEN_9 = _csr_io_privOp_ecall_T & _csr_io_privOp_ecall_T_1;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:115:34, :119:70, :210:36]
  always @(posedge clock) begin	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
    if (reset)	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
      pcReg <= 32'h80000000;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:78:22]
    else	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
      pcReg <= _pcu_io_dnpc;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:70:19, :78:22]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
      `FIRRTL_BEFORE_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
    initial begin	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
        `INIT_RANDOM_PROLOG_	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
        pcReg = _RANDOM[/*Zero width*/ 1'b0];	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7, :78:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
      `FIRRTL_AFTER_INITIAL	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Decoder decoder (	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
    .io_instr     (io_instr),
    .io_instrType (_decoder_io_instrType),
    .io_fuType    (_decoder_io_fuType),
    .io_opType    (_decoder_io_opType),
    .io_rs1       (_decoder_io_rs1),
    .io_rs2       (_decoder_io_rs2),
    .io_rd        (_decoder_io_rd),
    .io_imm       (_decoder_io_imm),
    .io_csrAddr   (_decoder_io_csrAddr)
  );
  ALU alu (	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:68:19]
    .io_in1    (in1),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:99:54, :100:9, :102:35]
    .io_in2    (in2),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:99:54, :101:9, :102:35, :107:9, :110:9]
    .io_opType (_GEN_1 | ~_GEN_2 ? _decoder_io_opType[6:0] : 7'h40),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :130:15, :133:21, :155:31, :156:19, :158:36, :159:19]
    .io_result (_alu_io_result)
  );
  BRU bru (	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:69:19]
    .io_rs1         (in1),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:99:54, :100:9, :102:35]
    .io_rs2         (in2),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:99:54, :101:9, :102:35, :107:9, :110:9]
    .io_opType      (_decoder_io_opType_3to0),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:152:17]
    .io_branchTaken (_bru_io_branchTaken)
  );
  PCU pcu (	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:70:19]
    .io_pc     (pcReg),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:78:22]
    .io_rs1    (_GEN_8 ? in1 : _GEN_9 ? _csr_io_dnpc : 32'h0),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:72:19, :99:54, :100:9, :102:35, :106:15, :193:{30,48}, :194:42, :210:{36,74}, :213:16, :218:16]
    .io_offset (_GEN_8 ? _decoder_io_imm : 32'h0),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :106:15, :193:{30,48}, :194:42, :210:74]
    .io_opType
      (_GEN_8
         ? ((&_decoder_io_opType_3to0) ? 4'hF : _GEN_4 ? 4'hE : 4'h5)
         : {1'h0, ~_GEN_9, 2'h0}),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7, :99:42, :136:{54,89}, :152:17, :193:{30,48}, :194:42, :195:21, :199:49, :200:21, :205:21, :210:{36,74}, :211:19, :216:19]
    .io_dnpc   (_pcu_io_dnpc)
  );
  LSU lsu (	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
    .io_addr            (result),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:155:31, :157:12, :158:36, :160:12, :161:37]
    .io_dataIn          (_GEN_7 ? _regfile_io_rdata2 : 32'h0),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:75:23, :106:15, :170:{30,59}, :172:19, :177:64]
    .io_mask
      (_GEN_7
         ? (_decoder_io_opType[1:0] == 2'h2
              ? 4'hF
              : {2'h0,
                 _decoder_io_opType[1:0] == 2'h1
                   ? 2'h3
                   : {1'h0, _decoder_io_opType[1:0] == 2'h0}})
         : _GEN_3
             ? (_decoder_io_opType[1:0] == 2'h2
                  ? 4'hF
                  : {2'h0,
                     _decoder_io_opType[1:0] == 2'h1
                       ? 2'h3
                       : {1'h0, _decoder_io_opType[1:0] == 2'h0}})
             : _decoder_io_opType[1:0] == 2'h2
                 ? 4'hF
                 : {2'h0,
                    _decoder_io_opType[1:0] == 2'h1
                      ? 2'h3
                      : {1'h0, _decoder_io_opType[1:0] == 2'h0}}),	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:18:{46,64}, home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7, :67:23, :99:42, :133:{21,36}, :136:{21,54}, :170:{30,59}, :173:17, :177:64, :180:17, :187:17]
    .io_wen             (_GEN_7),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:170:30]
    .io_ren             (~_GEN_7 & _GEN_3),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:133:36, :170:{30,59}, :176:16, :177:64]
    .io_sign
      (_GEN_7
         ? ~(_decoder_io_opType[2])
         : _GEN_3 ? ~(_decoder_io_opType[2]) : ~(_decoder_io_opType[2])),	// @[home/lj/Desktop/C_stage_core/playground/src/core/LSU.scala:17:{36,41}, home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :133:36, :170:{30,59}, :174:17, :177:64, :181:17, :188:17]
    .io_rdata           (_lsu_io_rdata),
    .io_mem_readData    (_memory_readData),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:73:22]
    .io_mem_readEnable  (_lsu_io_mem_readEnable),
    .io_mem_addr        (_lsu_io_mem_addr),
    .io_mem_writeEnable (_lsu_io_mem_writeEnable),
    .io_mem_writeMask   (_lsu_io_mem_writeMask),
    .io_mem_writeData   (_lsu_io_mem_writeData)
  );
  CSRU csr (	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:72:19]
    .clock           (clock),
    .reset           (reset),
    .io_csrOpType    (_decoder_io_opType[2:0]),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :114:20]
    .io_csrCmd_valid (_csr_io_privOp_ecall_T & (|(_decoder_io_opType[2:0]))),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23, :114:20, :115:{34,50,71}]
    .io_csrCmd_addr  (_decoder_io_csrAddr),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
    .io_csrCmd_rs1   (in1),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:99:54, :100:9, :102:35]
    .io_privOp_mret  (_csr_io_privOp_ecall_T & _csr_io_privOp_ecall_T_1 & io_instr[21]),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:115:34, :119:{70,89,100}]
    .io_privOp_ecall
      (_csr_io_privOp_ecall_T & _csr_io_privOp_ecall_T_1 & ~(io_instr[21])),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:115:34, :119:{70,100}, :120:{90,93}]
    .io_privOp_pc    (pcReg),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:78:22]
    .io_rdata        (_csr_io_rdata),
    .io_dnpc         (_csr_io_dnpc)
  );
  Memory memory (	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:73:22]
    .readData    (_memory_readData),
    .readEnable  (_lsu_io_mem_readEnable),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
    .addr        (_lsu_io_mem_addr),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
    .writeEnable (_lsu_io_mem_writeEnable),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
    .writeMask   (_lsu_io_mem_writeMask),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
    .writeData   (_lsu_io_mem_writeData)	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19]
  );
  RegFile regfile (	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:75:23]
    .clock     (clock),
    .reset     (reset),
    .io_rs1    (_decoder_io_rs1),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
    .io_rs2    (_decoder_io_rs2),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
    .io_rd     (_decoder_io_rd),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:67:23]
    .io_wen    (_GEN_1 | _GEN_3 | _GEN_5 | _GEN_6),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:130:{15,30}, :132:9, :133:{36,64}, :135:9, :136:{36,109}, :138:9, :139:{36,76}]
    .io_wdata
      (_GEN_1
         ? result
         : _GEN_3
             ? _lsu_io_rdata
             : _GEN_5 ? pcReg + 32'h4 : _GEN_6 ? _csr_io_rdata : 32'h0),	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:71:19, :72:19, :78:22, :106:15, :130:{15,30}, :131:11, :133:{36,64}, :134:11, :136:{36,109}, :137:{11,20}, :139:{36,76}, :140:11, :144:11, :155:31, :157:12, :158:36, :160:12, :161:37]
    .io_rdata1 (_regfile_io_rdata1),
    .io_rdata2 (_regfile_io_rdata2)
  );
  assign io_pc = pcReg;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7, :78:22]
  assign io_dnpc = _pcu_io_dnpc;	// @[home/lj/Desktop/C_stage_core/playground/src/top/top.scala:60:7, :70:19]
endmodule


// ----- 8< ----- FILE "./Memory.v" ----- 8< -----


    import "DPI-C" function bit[31:0] pmem_read(input logic[31:0] raddr);
    import "DPI-C" function void pmem_write(input logic[31:0] waddr, input logic[31:0] wdata, input byte wmask);

    module Memory(
      output reg[31:0] readData,
      input         readEnable,
      input  [31:0] addr,
      input         writeEnable,
      input  [3:0]  writeMask,
      input  [31:0] writeData
    );
      always @(*) begin
        if (readEnable) begin
          readData = pmem_read(addr);
        end else begin
          readData = 32'b0;
        end
      end

      always @(*) begin
        if (writeEnable) begin
          pmem_write(addr, writeData, {4'b0,writeMask});
        end
      end
    endmodule
    

// ----- 8< ----- FILE "./DPIModule.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.1

import "DPI-C" function void read_reg(input logic [31:0] signal[31:0]);

module DPIModule(
  input logic [31:0] regs_0,  input logic [31:0] regs_1,
  input logic [31:0] regs_2,  input logic [31:0] regs_3,
  input logic [31:0] regs_4,  input logic [31:0] regs_5,
  input logic [31:0] regs_6,  input logic [31:0] regs_7,
  input logic [31:0] regs_8,  input logic [31:0] regs_9,
  input logic [31:0] regs_10, input logic [31:0] regs_11,
  input logic [31:0] regs_12, input logic [31:0] regs_13,
  input logic [31:0] regs_14, input logic [31:0] regs_15,
  input logic [31:0] regs_16, input logic [31:0] regs_17,
  input logic [31:0] regs_18, input logic [31:0] regs_19,
  input logic [31:0] regs_20, input logic [31:0] regs_21,
  input logic [31:0] regs_22, input logic [31:0] regs_23,
  input logic [31:0] regs_24, input logic [31:0] regs_25,
  input logic [31:0] regs_26, input logic [31:0] regs_27,
  input logic [31:0] regs_28, input logic [31:0] regs_29,
  input logic [31:0] regs_30, input logic [31:0] regs_31
);

  logic [31:0] regs[32];

  always_comb begin
    regs[0]  = regs_0;  regs[1]  = regs_1;  regs[2]  = regs_2;  regs[3]  = regs_3;
    regs[4]  = regs_4;  regs[5]  = regs_5;  regs[6]  = regs_6;  regs[7]  = regs_7;
    regs[8]  = regs_8;  regs[9]  = regs_9;  regs[10] = regs_10; regs[11] = regs_11;
    regs[12] = regs_12; regs[13] = regs_13; regs[14] = regs_14; regs[15] = regs_15;
    regs[16] = regs_16; regs[17] = regs_17; regs[18] = regs_18; regs[19] = regs_19;
    regs[20] = regs_20; regs[21] = regs_21; regs[22] = regs_22; regs[23] = regs_23;
    regs[24] = regs_24; regs[25] = regs_25; regs[26] = regs_26; regs[27] = regs_27;
    regs[28] = regs_28; regs[29] = regs_29; regs[30] = regs_30; regs[31] = regs_31;

    read_reg(regs);
  end
endmodule

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----

DPIModule.sv
Memory.v
